language: python
sudo: required
dist: precise

install: "sudo apt-get update && sudo apt-get install -y python-dev && pip install -r requirements.txt && pip install -r dev-requirements.txt"
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=pypy
    - TOX_ENV=docs
    - TOX_ENV=pep8

script:
  - tox -c tox.ini -e $TOX_ENV

after_success:
  - coveralls
  - codecov
